import {
  ArrowRightOutlined,
  CodeSandboxOutlined,
  LockOutlined,
  MobileOutlined,
  UserOutlined,
  AccountBookOutlined,
  AimOutlined,
  ApartmentOutlined,
  DashboardOutlined,
  InsertRowAboveOutlined,
  LineChartOutlined,
  SmileOutlined,
  TeamOutlined,
  StarOutlined,
} from "@ant-design/icons";

export default {
  ArrowRight: <ArrowRightOutlined />,
  UserIcon: <UserOutlined />,
  LockIcon: <LockOutlined />,
  MobileIcon: <MobileOutlined />,
  CodeIcon: <CodeSandboxOutlined />,
  Dashboard: <DashboardOutlined />,
  Attendance: <LineChartOutlined />,
  Team: <TeamOutlined />,
  Department: <ApartmentOutlined />,
  Level: <AimOutlined />,
  Assessment: <InsertRowAboveOutlined />,
  Salary: <AccountBookOutlined />,
  RewardAndPunishment: <StarOutlined />,
  BarChart: <SmileOutlined />,
};
