import {
  ArrowRightOutlined,
  CodeSandboxOutlined,
  LockOutlined,
  MobileOutlined,
  UserOutlined,
  AccountBookOutlined,
  AimOutlined,
  ApartmentOutlined,
  DashboardOutlined,
  InsertRowAboveOutlined,
  LineChartOutlined,
  TeamOutlined,
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  DatabaseOutlined,
  BarChartOutlined,
  LogoutOutlined,
  CopyOutlined,
  DeleteOutlined,
  CloseCircleOutlined,
} from "@ant-design/icons";

export default {
  ArrowRight: <ArrowRightOutlined />,
  UserIcon: <UserOutlined />,
  LockIcon: <LockOutlined />,
  MobileIcon: <MobileOutlined />,
  CodeIcon: <CodeSandboxOutlined />,
  Dashboard: <DashboardOutlined />,
  Attendance: <LineChartOutlined />,
  Team: <TeamOutlined />,
  Department: <ApartmentOutlined />,
  Level: <AimOutlined />,
  Assessment: <InsertRowAboveOutlined />,
  Salary: <AccountBookOutlined />,
  RewardAndPunishment: <DatabaseOutlined />,
  BarChart: <BarChartOutlined />,
  LeftMenuArrow: <MenuFoldOutlined />,
  RightMenuArrow: <MenuUnfoldOutlined />,
  LogoutOut: <LogoutOutlined />,
  copy: <CopyOutlined />,
  del: <DeleteOutlined />,
  close: <CloseCircleOutlined />,
};
